services:
  # Serviço do Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Serviço da API Principal
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/usr/src/app/data/dev.db
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped

  # Serviço do Worker de Notificações
  worker:
    build: .
    # Sobrescreve o comando padrão do Dockerfile para iniciar o worker
    command: npm run start:worker
    environment:
      - DATABASE_URL=file:/usr/src/app/data/dev.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  db_data: